-- 코드를 작성해주세요
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A
WHERE A.SKILL_CODE & (SELECT SKILLCODES.CODE FROM SKILLCODES WHERE NAME = 'C#')
OR A.SKILL_CODE & (SELECT SKILLCODES.CODE FROM SKILLCODES WHERE NAME = 'Python')
ORDER BY A.ID 